### ISSUE TITLE
Not working anymore in Chrome and Firefox

### ISSUE THREAD

**Issue by mschroettle** [webrender/trello-collapse-columns#8]
The extension is not working anymore in Chrome 99.0.4844.51 and in firefox 97.0.2. Is there any way to fix this. Thanks.

**Comment by yorkfrog** [comment]
I hacked a fix on FF.
https://github.com/webrender/trello-collapse-lists/issues/9#issuecomment-1518669504

**Comment by webrender** [comment]
Hi there! I've pushed a fix this week (and published on FF/Chrome stores) that should resolve this issue.
