### ISSUE TITLE
Not working with the new Trello Theme

### ISSUE THREAD

**Issue by ForgottenHero** [webrender/trello-collapse-columns#9]
With the new Trello theme enabled, collapsed lists don't resize the column that's been collapsed anymore, leaving a gap.

![image](https://user-images.githubusercontent.com/4233945/227095583-ebe8567d-bca4-4f09-85f7-51baecccb885.png)

![image](https://user-images.githubusercontent.com/4233945/227095469-f73debc0-5b5f-443c-9de1-46eedd822792.png)

**Comment by johnknoop** [comment]
🍿

**Comment by yorkfrog** [comment]
I'm seeing same behaviour.
I have fiddle with in page CSS and can get it to work again but don't know how to rebuild the XPI as it appears to be signed.
![ksnip_20230422-142635](https://user-images.githubusercontent.com/31819562/233787913-1cae23eb-57f7-4967-950c-ffd6efe92bbf.png)

Disabling the CSS margin attribute in `body.ff-modernization-update .list-wrapper` rule seems to get spacing usable again.
 -C

**Comment by matt22207** [comment]
+1

**Comment by yorkfrog** [comment]
I run Firefox on Ubuntu and FF has the ability to inject CSS in to any domain so have managed to fix this on FF.
this post explains how to inject CSS: https://superuser.com/questions/318912/how-can-i-override-the-css-of-a-site-in-firefox-with-usercontent-css

My userContent.css looks like this: 
```
@-moz-document domain(trello.com) {
/* fix FF TRello Colapse Lists ext after Trello 2023 update */
    .js-list.-closed {
        margin-right: -182px !important;
    }
}
```
You have to restart FF after the changes.
And now the Trello pages look like my screen shot above :)  Hope this helps others. 
-C

**Comment by webrender** [comment]
Hi folks! I've just published updates to the extension that should resolve this issue.
